
package ejbs;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.2-02/08/2010 05:22 PM(mockbuild)-SNAPSHOT
 * Generated source version: 2.0
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://ejbs")
public interface HelloWorld {


    /**
     * 
     * @return
     *     returns ejbs.HelloWorldTO
     */
    @WebMethod(action = "sayMoreHello")
    @WebResult(name = "sayMoreHelloReturn", targetNamespace = "")
    @RequestWrapper(localName = "sayMoreHello", targetNamespace = "http://ejbs", className = "ejbs.SayMoreHello")
    @ResponseWrapper(localName = "sayMoreHelloResponse", targetNamespace = "http://ejbs", className = "ejbs.SayMoreHelloResponse")
    public HelloWorldTO sayMoreHello();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "sayHello")
    @WebResult(name = "sayHelloReturn", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ejbs", className = "ejbs.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ejbs", className = "ejbs.SayHelloResponse")
    public String sayHello();

}
